# Generated by Django 5.1.6 on 2025-06-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_workout_distance_workout_reps_workout_sets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinerecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
